# Generated by Django 3.1.4 on 2021-01-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('desciption', models.TextField()),
                ('price', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
    ]
