# Generated by Django 3.1.4 on 2021-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.TextField(null=True),
        ),
    ]
