# Generated by Django 3.1.4 on 2021-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
