# Generated by Django 3.1.4 on 2021-01-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210123_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
    ]
